
SERVER:
  ADDRESS: 127.0.0.1
  PORT: 8000
  URL_PREFIX: http://localhost:8000 # 地址前缀，不以/结尾
  SECRET_KEYS: 'this is secret key' # 加密session用的key
  MAXAGE: 0 # 静态资源缓存时间,单位ms

MONGODB: # mongodb配置
  HOSTNAME: 127.0.0.1
  DATABASE: thupc2018_test

MYSUBMAIL: # www.mysubmail.com
  APPID: 23333
  APPKEY: xxxxxxxxxxxxxxxxxx
  VERIFY_CODE_PROJECT: yyyyy # 验证码项目id
